### ISSUE TITLE
Gradio Interface is not optimized. Always throws CUDA out of Memory error even on 24GB of VRAM

### ISSUE THREAD

**Issue by C0nsumption** [VAST-AI-Research/TripoSR#4]
![image](https://github.com/VAST-AI-Research/TripoSR/assets/98207055/c850e8e4-784b-43a4-8055-82908c8fb758)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB. GPU 0 has a total capacity of 23.67 GiB of which 2.72 GiB is free. Including non-PyTorch memory, this process has 20.58 GiB memory in use. Of the allocated memory 20.20 GiB is allocated by PyTorch, and 68.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by C0nsumption** [comment]
Got it working.
In **gradio_app.py**, we have to set the default chunk size as we do in **run.py**.
By default, the cli for **run.py sets the chunk_size to 8192**  (lines 58 to 63 in run.py):

![image](https://github.com/VAST-AI-Research/TripoSR/assets/98207055/5e2d211f-bf7d-4dfc-a301-02781b90925d)

And then passes that value on line 108 to the actual renderer:
![image](https://github.com/VAST-AI-Research/TripoSR/assets/98207055/bd2fcd9a-a494-4b49-9dab-e5f1e1e4f010)

We can do this in the gradio app manually although it would maybe make sense to lift this value up into the actual interface if it is crucial for operation and quality. Anyway, I got it working by adding model.renderer.set_chunk_size(8192) into **gradio_app.py**
after line 25:

![image](https://github.com/VAST-AI-Research/TripoSR/assets/98207055/767c6368-942c-42fa-a85b-b8b5c18c2152)

**Comment by bennyguo** [comment]
Thanks for reporting! I've changed the default chunk size to 8192 in the gradio app.

**Comment by dongyun-kim-arch** [comment]
Had the same error... I am using 24GB vram GPU, but whenever I run the script, it throws the CUDA memory error. Already tried to change foreground ratio and marching cubes resolution, but doesn't work...

**Comment by pookiefoof** [comment]
> Had the same error... I am using 24GB vram GPU, but whenever I run the script, it throws the CUDA memory error. Already tried to change foreground ratio and marching cubes resolution, but doesn't work...

Have you tried to decrease the `chunk_size`?

**Comment by dongyun-kim-arch** [comment]
Yes… tried half size 4096.. is it not enough for 24 vram? I tried sample images in repo
